%%% KBS flux data processing
%%% Using gapfileld data from REddyProc


clear all
close all


%%% Read in T1 site data
T1 = dlmread("T1\T1 output.txt",'\t',17522,0);
T1(T1 == -9999) = NaN;
T1(T1 == -10000) = NaN;

%%% Data Selection

NEE=T1(:,4);
Tair=T1(:,8);
rH=T1(:,9);
VPD=T1(:,10);
NEE_f=T1(:,16);
LE_f=T1(:,25);
H_f=T1(:,34);
Rg_f=T1(:,43);
VPD_f=T1(:,52);
rH_f=T1(:,61);
Tair_f=T1(:,70);
Reco=T1(:,83);
GPP=T1(:,84);
Reco_DT=T1(:,106);
GPP_DT=T1(:,107);




%%% Output T1 Site Data %%%

DataOut = table(...
NEE,...
NEE_f,...
LE_f,...
H_f,...
Rg_f,...
Reco,...
GPP,...
Reco_DT,...
GPP_DT,...
Tair,...
Tair_f,...
rH,...
rH_f,...
VPD,...
VPD_f);

writetable(DataOut,'ANN\T1_data.csv')


%%% calc DAILY T1 Site Data %%%

n=48;
NEE_day=arrayfun(@(i) nanmean(NEE(i:i+n-1)),1:n:length(NEE)-n+1)';
NEE_f_day=arrayfun(@(i) nanmean(NEE_f(i:i+n-1)),1:n:length(NEE_f)-n+1)';
LE_f_day=arrayfun(@(i) nanmean(LE_f(i:i+n-1)),1:n:length(LE_f)-n+1)';
H_f_day=arrayfun(@(i) nanmean(H_f(i:i+n-1)),1:n:length(H_f)-n+1)';
Rg_f_day=arrayfun(@(i) nanmean(Rg_f(i:i+n-1)),1:n:length(Rg_f)-n+1)';
Reco_day=arrayfun(@(i) nanmean(Reco(i:i+n-1)),1:n:length(Reco)-n+1)';
GPP_day=arrayfun(@(i) nanmean(GPP(i:i+n-1)),1:n:length(GPP)-n+1)';
Reco_DT_day=arrayfun(@(i) nanmean(Reco_DT(i:i+n-1)),1:n:length(Reco_DT)-n+1)';
GPP_DT_day=arrayfun(@(i) nanmean(GPP_DT(i:i+n-1)),1:n:length(GPP_DT)-n+1)';
Tair_day=arrayfun(@(i) nanmean(Tair(i:i+n-1)),1:n:length(Tair)-n+1)';
Tair_f_day=arrayfun(@(i) nanmean(Tair_f(i:i+n-1)),1:n:length(Tair_f)-n+1)';
rH_day=arrayfun(@(i) nanmean(rH(i:i+n-1)),1:n:length(rH)-n+1)';
rH_f_day=arrayfun(@(i) nanmean(rH_f(i:i+n-1)),1:n:length(rH_f)-n+1)';
VPD_day=arrayfun(@(i) nanmean(VPD(i:i+n-1)),1:n:length(VPD)-n+1)';
VPD_f_day=arrayfun(@(i) nanmean(VPD_f(i:i+n-1)),1:n:length(VPD_f)-n+1)';


%%% Output DAILY T1 Site Data %%%

DataOut = table(...
NEE_day,...
NEE_f_day,...
LE_f_day,...
H_f_day,...
Rg_f_day,...
Reco_day,...
GPP_day,...
Reco_DT_day,...
GPP_DT_day,...
Tair_day,...
Tair_f_day,...
rH_day,...
rH_f_day,...
VPD_day,...
VPD_f_day);


writetable(DataOut,'ANN\T1_day_data.csv')

%%% End Output T1 Data %%%
clear all
close all





%%% Read in T2 site data
T2 = dlmread("T2\T2 output.txt",'\t',17522,0);
T2(T2 == -9999) = NaN;
T2(T2 == -10000) = NaN;

%%% Data Selection

NEE=T2(:,4);
Tair=T2(:,8);
rH=T2(:,9);
VPD=T2(:,10);
NEE_f=T2(:,16);
LE_f=T2(:,25);
H_f=T2(:,34);
Rg_f=T2(:,43);
VPD_f=T2(:,52);
rH_f=T2(:,61);
Tair_f=T2(:,70);
Reco=T2(:,83);
GPP=T2(:,84);
Reco_DT=T2(:,106);
GPP_DT=T2(:,107);




%%% Output T2 Site Data %%%

DataOut = table(...
NEE,...
NEE_f,...
LE_f,...
H_f,...
Rg_f,...
Reco,...
GPP,...
Reco_DT,...
GPP_DT,...
Tair,...
Tair_f,...
rH,...
rH_f,...
VPD,...
VPD_f);

writetable(DataOut,'ANN\T2_data.csv')


%%% calc DAILY T2 Site Data %%%

n=48;
NEE_day=arrayfun(@(i) nanmean(NEE(i:i+n-1)),1:n:length(NEE)-n+1)';
NEE_f_day=arrayfun(@(i) nanmean(NEE_f(i:i+n-1)),1:n:length(NEE_f)-n+1)';
LE_f_day=arrayfun(@(i) nanmean(LE_f(i:i+n-1)),1:n:length(LE_f)-n+1)';
H_f_day=arrayfun(@(i) nanmean(H_f(i:i+n-1)),1:n:length(H_f)-n+1)';
Rg_f_day=arrayfun(@(i) nanmean(Rg_f(i:i+n-1)),1:n:length(Rg_f)-n+1)';
Reco_day=arrayfun(@(i) nanmean(Reco(i:i+n-1)),1:n:length(Reco)-n+1)';
GPP_day=arrayfun(@(i) nanmean(GPP(i:i+n-1)),1:n:length(GPP)-n+1)';
Reco_DT_day=arrayfun(@(i) nanmean(Reco_DT(i:i+n-1)),1:n:length(Reco_DT)-n+1)';
GPP_DT_day=arrayfun(@(i) nanmean(GPP_DT(i:i+n-1)),1:n:length(GPP_DT)-n+1)';
Tair_day=arrayfun(@(i) nanmean(Tair(i:i+n-1)),1:n:length(Tair)-n+1)';
Tair_f_day=arrayfun(@(i) nanmean(Tair_f(i:i+n-1)),1:n:length(Tair_f)-n+1)';
rH_day=arrayfun(@(i) nanmean(rH(i:i+n-1)),1:n:length(rH)-n+1)';
rH_f_day=arrayfun(@(i) nanmean(rH_f(i:i+n-1)),1:n:length(rH_f)-n+1)';
VPD_day=arrayfun(@(i) nanmean(VPD(i:i+n-1)),1:n:length(VPD)-n+1)';
VPD_f_day=arrayfun(@(i) nanmean(VPD_f(i:i+n-1)),1:n:length(VPD_f)-n+1)';


%%% Output DAILY T2 Site Data %%%

DataOut = table(...
NEE_day,...
NEE_f_day,...
LE_f_day,...
H_f_day,...
Rg_f_day,...
Reco_day,...
GPP_day,...
Reco_DT_day,...
GPP_DT_day,...
Tair_day,...
Tair_f_day,...
rH_day,...
rH_f_day,...
VPD_day,...
VPD_f_day);


writetable(DataOut,'ANN\T2_day_data.csv')

%%% End Output T2 Data %%%



clear all
close all


%%% Read in T3 site data
T3 = dlmread("T3\T3 output.txt",'\t',17522,0);
T3(T3 == -9999) = NaN;
T3(T3 == -10000) = NaN;

%%% Data Selection

NEE=T3(:,4);
Tair=T3(:,8);
rH=T3(:,9);
VPD=T3(:,10);
NEE_f=T3(:,16);
LE_f=T3(:,25);
H_f=T3(:,34);
Rg_f=T3(:,43);
VPD_f=T3(:,52);
rH_f=T3(:,61);
Tair_f=T3(:,70);
Reco=T3(:,83);
GPP=T3(:,84);
Reco_DT=T3(:,106);
GPP_DT=T3(:,107);




%%% Output T3 Site Data %%%

DataOut = table(...
NEE,...
NEE_f,...
LE_f,...
H_f,...
Rg_f,...
Reco,...
GPP,...
Reco_DT,...
GPP_DT,...
Tair,...
Tair_f,...
rH,...
rH_f,...
VPD,...
VPD_f);

writetable(DataOut,'ANN\T3_data.csv')


%%% calc DAILY T3 Site Data %%%

n=48;
NEE_day=arrayfun(@(i) nanmean(NEE(i:i+n-1)),1:n:length(NEE)-n+1)';
NEE_f_day=arrayfun(@(i) nanmean(NEE_f(i:i+n-1)),1:n:length(NEE_f)-n+1)';
LE_f_day=arrayfun(@(i) nanmean(LE_f(i:i+n-1)),1:n:length(LE_f)-n+1)';
H_f_day=arrayfun(@(i) nanmean(H_f(i:i+n-1)),1:n:length(H_f)-n+1)';
Rg_f_day=arrayfun(@(i) nanmean(Rg_f(i:i+n-1)),1:n:length(Rg_f)-n+1)';
Reco_day=arrayfun(@(i) nanmean(Reco(i:i+n-1)),1:n:length(Reco)-n+1)';
GPP_day=arrayfun(@(i) nanmean(GPP(i:i+n-1)),1:n:length(GPP)-n+1)';
Reco_DT_day=arrayfun(@(i) nanmean(Reco_DT(i:i+n-1)),1:n:length(Reco_DT)-n+1)';
GPP_DT_day=arrayfun(@(i) nanmean(GPP_DT(i:i+n-1)),1:n:length(GPP_DT)-n+1)';
Tair_day=arrayfun(@(i) nanmean(Tair(i:i+n-1)),1:n:length(Tair)-n+1)';
Tair_f_day=arrayfun(@(i) nanmean(Tair_f(i:i+n-1)),1:n:length(Tair_f)-n+1)';
rH_day=arrayfun(@(i) nanmean(rH(i:i+n-1)),1:n:length(rH)-n+1)';
rH_f_day=arrayfun(@(i) nanmean(rH_f(i:i+n-1)),1:n:length(rH_f)-n+1)';
VPD_day=arrayfun(@(i) nanmean(VPD(i:i+n-1)),1:n:length(VPD)-n+1)';
VPD_f_day=arrayfun(@(i) nanmean(VPD_f(i:i+n-1)),1:n:length(VPD_f)-n+1)';


%%% Output DAILY T3 Site Data %%%

DataOut = table(...
NEE_day,...
NEE_f_day,...
LE_f_day,...
H_f_day,...
Rg_f_day,...
Reco_day,...
GPP_day,...
Reco_DT_day,...
GPP_DT_day,...
Tair_day,...
Tair_f_day,...
rH_day,...
rH_f_day,...
VPD_day,...
VPD_f_day);


writetable(DataOut,'ANN\T3_day_data.csv')

%%% End Output T3 Data %%%




clear all
close all


%%% Read in T4 site data
T4 = dlmread("T4\T4 output.txt",'\t',17522,0);
T4(T4 == -9999) = NaN;
T4(T4 == -10000) = NaN;

%%% Data Selection

NEE=T4(:,4);
Tair=T4(:,8);
rH=T4(:,9);
VPD=T4(:,10);
NEE_f=T4(:,16);
LE_f=T4(:,25);
H_f=T4(:,34);
Rg_f=T4(:,43);
VPD_f=T4(:,52);
rH_f=T4(:,61);
Tair_f=T4(:,70);
Reco=T4(:,83);
GPP=T4(:,84);
Reco_DT=T4(:,106);
GPP_DT=T4(:,107);




%%% Output T4 Site Data %%%

DataOut = table(...
NEE,...
NEE_f,...
LE_f,...
H_f,...
Rg_f,...
Reco,...
GPP,...
Reco_DT,...
GPP_DT,...
Tair,...
Tair_f,...
rH,...
rH_f,...
VPD,...
VPD_f);

writetable(DataOut,'ANN\T4_data.csv')


%%% calc DAILY T4 Site Data %%%

n=48;
NEE_day=arrayfun(@(i) nanmean(NEE(i:i+n-1)),1:n:length(NEE)-n+1)';
NEE_f_day=arrayfun(@(i) nanmean(NEE_f(i:i+n-1)),1:n:length(NEE_f)-n+1)';
LE_f_day=arrayfun(@(i) nanmean(LE_f(i:i+n-1)),1:n:length(LE_f)-n+1)';
H_f_day=arrayfun(@(i) nanmean(H_f(i:i+n-1)),1:n:length(H_f)-n+1)';
Rg_f_day=arrayfun(@(i) nanmean(Rg_f(i:i+n-1)),1:n:length(Rg_f)-n+1)';
Reco_day=arrayfun(@(i) nanmean(Reco(i:i+n-1)),1:n:length(Reco)-n+1)';
GPP_day=arrayfun(@(i) nanmean(GPP(i:i+n-1)),1:n:length(GPP)-n+1)';
Reco_DT_day=arrayfun(@(i) nanmean(Reco_DT(i:i+n-1)),1:n:length(Reco_DT)-n+1)';
GPP_DT_day=arrayfun(@(i) nanmean(GPP_DT(i:i+n-1)),1:n:length(GPP_DT)-n+1)';
Tair_day=arrayfun(@(i) nanmean(Tair(i:i+n-1)),1:n:length(Tair)-n+1)';
Tair_f_day=arrayfun(@(i) nanmean(Tair_f(i:i+n-1)),1:n:length(Tair_f)-n+1)';
rH_day=arrayfun(@(i) nanmean(rH(i:i+n-1)),1:n:length(rH)-n+1)';
rH_f_day=arrayfun(@(i) nanmean(rH_f(i:i+n-1)),1:n:length(rH_f)-n+1)';
VPD_day=arrayfun(@(i) nanmean(VPD(i:i+n-1)),1:n:length(VPD)-n+1)';
VPD_f_day=arrayfun(@(i) nanmean(VPD_f(i:i+n-1)),1:n:length(VPD_f)-n+1)';


%%% Output DAILY T4 Site Data %%%

DataOut = table(...
NEE_day,...
NEE_f_day,...
LE_f_day,...
H_f_day,...
Rg_f_day,...
Reco_day,...
GPP_day,...
Reco_DT_day,...
GPP_DT_day,...
Tair_day,...
Tair_f_day,...
rH_day,...
rH_f_day,...
VPD_day,...
VPD_f_day);


writetable(DataOut,'ANN\T4_day_data.csv')

%%% End Output T4 Data %%%



clear all
close all


%%% Read in T5 site data
T5 = dlmread("T5\T5 output.txt",'\t',17522,0);
T5(T5 == -9999) = NaN;
T5(T5 == -10000) = NaN;

%%% Data Selection

NEE=T5(:,4);
Tair=T5(:,8);
rH=T5(:,9);
VPD=T5(:,10);
NEE_f=T5(:,16);
LE_f=T5(:,25);
H_f=T5(:,34);
Rg_f=T5(:,43);
VPD_f=T5(:,52);
rH_f=T5(:,61);
Tair_f=T5(:,70);
Reco=T5(:,83);
GPP=T5(:,84);
Reco_DT=T5(:,106);
GPP_DT=T5(:,107);




%%% Output T5 Site Data %%%

DataOut = table(...
NEE,...
NEE_f,...
LE_f,...
H_f,...
Rg_f,...
Reco,...
GPP,...
Reco_DT,...
GPP_DT,...
Tair,...
Tair_f,...
rH,...
rH_f,...
VPD,...
VPD_f);

writetable(DataOut,'ANN\T5_data.csv')


%%% calc DAILY T5 Site Data %%%

n=48;
NEE_day=arrayfun(@(i) nanmean(NEE(i:i+n-1)),1:n:length(NEE)-n+1)';
NEE_f_day=arrayfun(@(i) nanmean(NEE_f(i:i+n-1)),1:n:length(NEE_f)-n+1)';
LE_f_day=arrayfun(@(i) nanmean(LE_f(i:i+n-1)),1:n:length(LE_f)-n+1)';
H_f_day=arrayfun(@(i) nanmean(H_f(i:i+n-1)),1:n:length(H_f)-n+1)';
Rg_f_day=arrayfun(@(i) nanmean(Rg_f(i:i+n-1)),1:n:length(Rg_f)-n+1)';
Reco_day=arrayfun(@(i) nanmean(Reco(i:i+n-1)),1:n:length(Reco)-n+1)';
GPP_day=arrayfun(@(i) nanmean(GPP(i:i+n-1)),1:n:length(GPP)-n+1)';
Reco_DT_day=arrayfun(@(i) nanmean(Reco_DT(i:i+n-1)),1:n:length(Reco_DT)-n+1)';
GPP_DT_day=arrayfun(@(i) nanmean(GPP_DT(i:i+n-1)),1:n:length(GPP_DT)-n+1)';
Tair_day=arrayfun(@(i) nanmean(Tair(i:i+n-1)),1:n:length(Tair)-n+1)';
Tair_f_day=arrayfun(@(i) nanmean(Tair_f(i:i+n-1)),1:n:length(Tair_f)-n+1)';
rH_day=arrayfun(@(i) nanmean(rH(i:i+n-1)),1:n:length(rH)-n+1)';
rH_f_day=arrayfun(@(i) nanmean(rH_f(i:i+n-1)),1:n:length(rH_f)-n+1)';
VPD_day=arrayfun(@(i) nanmean(VPD(i:i+n-1)),1:n:length(VPD)-n+1)';
VPD_f_day=arrayfun(@(i) nanmean(VPD_f(i:i+n-1)),1:n:length(VPD_f)-n+1)';


%%% Output DAILY T5 Site Data %%%

DataOut = table(...
NEE_day,...
NEE_f_day,...
LE_f_day,...
H_f_day,...
Rg_f_day,...
Reco_day,...
GPP_day,...
Reco_DT_day,...
GPP_DT_day,...
Tair_day,...
Tair_f_day,...
rH_day,...
rH_f_day,...
VPD_day,...
VPD_f_day);


writetable(DataOut,'ANN\T5_day_data.csv')

%%% End Output T5 Data %%%



clear all
close all


%%% Read in T6 site data
T6 = dlmread("T6\T6 output.txt",'\t',17522,0);
T6(T6 == -9999) = NaN;
T6(T6 == -10000) = NaN;

%%% Data Selection

NEE=T6(:,4);
Tair=T6(:,8);
rH=T6(:,9);
VPD=T6(:,10);
NEE_f=T6(:,16);
LE_f=T6(:,25);
H_f=T6(:,34);
Rg_f=T6(:,43);
VPD_f=T6(:,52);
rH_f=T6(:,61);
Tair_f=T6(:,70);
Reco=T6(:,83);
GPP=T6(:,84);
Reco_DT=T6(:,106);
GPP_DT=T6(:,107);




%%% Output T6 Site Data %%%

DataOut = table(...
NEE,...
NEE_f,...
LE_f,...
H_f,...
Rg_f,...
Reco,...
GPP,...
Reco_DT,...
GPP_DT,...
Tair,...
Tair_f,...
rH,...
rH_f,...
VPD,...
VPD_f);

writetable(DataOut,'ANN\T6_data.csv')


%%% calc DAILY T6 Site Data %%%

n=48;
NEE_day=arrayfun(@(i) nanmean(NEE(i:i+n-1)),1:n:length(NEE)-n+1)';
NEE_f_day=arrayfun(@(i) nanmean(NEE_f(i:i+n-1)),1:n:length(NEE_f)-n+1)';
LE_f_day=arrayfun(@(i) nanmean(LE_f(i:i+n-1)),1:n:length(LE_f)-n+1)';
H_f_day=arrayfun(@(i) nanmean(H_f(i:i+n-1)),1:n:length(H_f)-n+1)';
Rg_f_day=arrayfun(@(i) nanmean(Rg_f(i:i+n-1)),1:n:length(Rg_f)-n+1)';
Reco_day=arrayfun(@(i) nanmean(Reco(i:i+n-1)),1:n:length(Reco)-n+1)';
GPP_day=arrayfun(@(i) nanmean(GPP(i:i+n-1)),1:n:length(GPP)-n+1)';
Reco_DT_day=arrayfun(@(i) nanmean(Reco_DT(i:i+n-1)),1:n:length(Reco_DT)-n+1)';
GPP_DT_day=arrayfun(@(i) nanmean(GPP_DT(i:i+n-1)),1:n:length(GPP_DT)-n+1)';
Tair_day=arrayfun(@(i) nanmean(Tair(i:i+n-1)),1:n:length(Tair)-n+1)';
Tair_f_day=arrayfun(@(i) nanmean(Tair_f(i:i+n-1)),1:n:length(Tair_f)-n+1)';
rH_day=arrayfun(@(i) nanmean(rH(i:i+n-1)),1:n:length(rH)-n+1)';
rH_f_day=arrayfun(@(i) nanmean(rH_f(i:i+n-1)),1:n:length(rH_f)-n+1)';
VPD_day=arrayfun(@(i) nanmean(VPD(i:i+n-1)),1:n:length(VPD)-n+1)';
VPD_f_day=arrayfun(@(i) nanmean(VPD_f(i:i+n-1)),1:n:length(VPD_f)-n+1)';


%%% Output DAILY T6 Site Data %%%

DataOut = table(...
NEE_day,...
NEE_f_day,...
LE_f_day,...
H_f_day,...
Rg_f_day,...
Reco_day,...
GPP_day,...
Reco_DT_day,...
GPP_DT_day,...
Tair_day,...
Tair_f_day,...
rH_day,...
rH_f_day,...
VPD_day,...
VPD_f_day);


writetable(DataOut,'ANN\T6_day_data.csv')

%%% End Output T6 Data %%%



clear all
close all


%%% Read in T7 site data
T7 = dlmread("T7\T7 output.txt",'\t',17522,0);
T7(T7 == -9999) = NaN;
T7(T7 == -10000) = NaN;

%%% Data Selection

NEE=T7(:,4);
Tair=T7(:,8);
rH=T7(:,9);
VPD=T7(:,10);
NEE_f=T7(:,16);
LE_f=T7(:,25);
H_f=T7(:,34);
Rg_f=T7(:,43);
VPD_f=T7(:,52);
rH_f=T7(:,61);
Tair_f=T7(:,70);
Reco=T7(:,83);
GPP=T7(:,84);
Reco_DT=T7(:,106);
GPP_DT=T7(:,107);




%%% Output T7 Site Data %%%

DataOut = table(...
NEE,...
NEE_f,...
LE_f,...
H_f,...
Rg_f,...
Reco,...
GPP,...
Reco_DT,...
GPP_DT,...
Tair,...
Tair_f,...
rH,...
rH_f,...
VPD,...
VPD_f);

writetable(DataOut,'ANN\T7_data.csv')


%%% calc DAILY T7 Site Data %%%

n=48;
NEE_day=arrayfun(@(i) nanmean(NEE(i:i+n-1)),1:n:length(NEE)-n+1)';
NEE_f_day=arrayfun(@(i) nanmean(NEE_f(i:i+n-1)),1:n:length(NEE_f)-n+1)';
LE_f_day=arrayfun(@(i) nanmean(LE_f(i:i+n-1)),1:n:length(LE_f)-n+1)';
H_f_day=arrayfun(@(i) nanmean(H_f(i:i+n-1)),1:n:length(H_f)-n+1)';
Rg_f_day=arrayfun(@(i) nanmean(Rg_f(i:i+n-1)),1:n:length(Rg_f)-n+1)';
Reco_day=arrayfun(@(i) nanmean(Reco(i:i+n-1)),1:n:length(Reco)-n+1)';
GPP_day=arrayfun(@(i) nanmean(GPP(i:i+n-1)),1:n:length(GPP)-n+1)';
Reco_DT_day=arrayfun(@(i) nanmean(Reco_DT(i:i+n-1)),1:n:length(Reco_DT)-n+1)';
GPP_DT_day=arrayfun(@(i) nanmean(GPP_DT(i:i+n-1)),1:n:length(GPP_DT)-n+1)';
Tair_day=arrayfun(@(i) nanmean(Tair(i:i+n-1)),1:n:length(Tair)-n+1)';
Tair_f_day=arrayfun(@(i) nanmean(Tair_f(i:i+n-1)),1:n:length(Tair_f)-n+1)';
rH_day=arrayfun(@(i) nanmean(rH(i:i+n-1)),1:n:length(rH)-n+1)';
rH_f_day=arrayfun(@(i) nanmean(rH_f(i:i+n-1)),1:n:length(rH_f)-n+1)';
VPD_day=arrayfun(@(i) nanmean(VPD(i:i+n-1)),1:n:length(VPD)-n+1)';
VPD_f_day=arrayfun(@(i) nanmean(VPD_f(i:i+n-1)),1:n:length(VPD_f)-n+1)';


%%% Output DAILY T7 Site Data %%%

DataOut = table(...
NEE_day,...
NEE_f_day,...
LE_f_day,...
H_f_day,...
Rg_f_day,...
Reco_day,...
GPP_day,...
Reco_DT_day,...
GPP_DT_day,...
Tair_day,...
Tair_f_day,...
rH_day,...
rH_f_day,...
VPD_day,...
VPD_f_day);


writetable(DataOut,'ANN\T7_day_data.csv')

%%% End Output T7 Data %%%

clear all
close all
